@host = http://localhost:8080

GET {{host}}/

###
# @name login
POST {{host}}/user/login
Content-type: application/json

{
    "email": "test@test.com",
    "password": "test123"
}

###
POST {{host}}/user/register
Content-type: application/json

{
    "email": "test1@test.com",
    "password": "test123"
}


@authToken = {{login.response.body.token}}

###
GET {{host}}/user/authenticated
Content-type: application/json
Authorization: Bearer {{authToken}}

